### ISSUE TITLE
Local connection not working with Ubuntu Server

### ISSUE THREAD

**Issue by frogger72** [djaydev/docker-virt-manager#1]
I'm having trouble getting the connection to qemu:///system working when using it in Ubuntu. I've changed listen_addr to 0.0.0.0 in /etc/libvirt/libvirtd.conf (and restarted the service) and installed netcat. Is there anything else I should do?

**Comment by djaydev** [comment]
@frogger72 
I always use SSH from the docker to the local host.  

Ensure your local host is accepting SSH connections
in the Docker container WebUI or VNC UI
   go File > Add Connection
    Hypervisor: QEMU
    Select connect to remote host over SSH
    Hostname: the internal network IP of your server
    Hit connect
