### ISSUE TITLE
stoping as soon as you run it.

### ISSUE THREAD

**Issue by dialloamadou** [djaydev/docker-virt-manager#2]
Failed to generate UUID: Could not read /dev/urandom: Is a directory

**Comment by djaydev** [comment]
From what I can tell, your host machine doesn't have the file "dev/unrandom" and when you mapped it to the docker container it created a directory.  What host OS are you using?

**Comment by dialloamadou** [comment]
Unraid docker

**Comment by djaydev** [comment]
I'm not an Unraid expert, but you have to figure out why your Unraid host doesn't have /dev/urandom.  

The first thing I would do is remove Virt-Manager, reboot Unraid, start array, login to Unraid's commandline console and type "ls /dev".  Look for /dev/urandom in the list.  If it's not there, Virt-Manager won't work on your Unraid.  

If /dev/urandom is in there, add Virt-Manager docker back, but before starting it click edit next to "/dev/urandom" and make sure " /dev/urandom" is set for container path and host path.

That's all I got, I use Unraid too and my Unraid host already had /dev/urandom, I didn't do anything to add it.

**Comment by dialloamadou** [comment]
yes, that worked. I needed to manually add the path to the file /dev/urandom

**Comment by djaydev** [comment]
awesome news!
